### PR TITLE
export RUBYLIB variable.

### PR DESCRIPTION
**Pull request by mikemcquaid**
This is needed for it to be passed into subprocesses. If you're using `rbenv` or some other Ruby wrappers this is needed and has no harm when it is not needed.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@infininight Any thoughts on this?

**Comment by noniq** [comment]
Hm, is this really necessary for commands using TextMate’s `ruby18` shim? As far as i understand, this shim should be completely unaffected by `rbenv`, `rvm` and co.

**Comment by mikemcquaid** [comment]
If you want to use a `TM_RUBY` that's pointing to something with `rbenv`: it's necessary, as far as I can tell.

**Comment by noniq** [comment]
Sorry, it took me until now to understand that the bundle’s command are already using `$RUBYLIB` and this pull request is only about explicitly exporting it. Seems fine!

**Comment by mikemcquaid** [comment]
Thanks @noniq! I guess you don't have merge access, though :sob:

**Comment by noniq** [comment]
No, unfortunately not :-/

**Comment by infininight** [comment]
Pulled as cd9138c87cca189100b0d6c2cfe1f72fb912239c, thanks for the PR, sorry for the delay.

**Comment by mikemcquaid** [comment]
Thanks @infininight!

**Pull request closed without merging**
